cargo-features = ["profile-rustflags"]

[package]
name = "waygaps"
version = "0.1.2"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/Ind-E/waygaps"
description = "Configurable hot corners and hot edges for wayland"
keywords = ["wayland"]
categories = ["command-line-utilities", "no-std"]

[features]
schema = ["dep:schemars", "dep:serde_json"]

[dependencies]
origin = { version = "0.26.2", default-features = false, features = [
    "origin-start",
    "signal",
] }
rustix = { version = "1.1.4", default-features = false, features = [
    "event",
    "mm",
    "runtime",
    "stdio",
    "termios",
] }
serde = { version = "1.0.228", default-features = false, features = [
    "derive",
    "alloc",
    "rc",
] }
smallvec = { version = "1.15.1", default-features = false, features = [
    "union",
] }
talc = { version = "5.0.3", default-features = false, features = ["nightly"] }
toml = { version = "1.0.3", default-features = false, features = [
    "serde",
    "parse",
] }
waybackend = { version = "0.10.1", default-features = false }

schemars = { version = "1.2.1", default-features = false, features = [
    "derive",
], optional = true }
serde_json = { version = "1.0.149", default-features = false, features = [
    "alloc",
], optional = true }
spinning_top = { version = "0.3.0", default-features = false }

[build-dependencies]
waybackend-scanner = { version = "0.10.1", features = ["build-script"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1
strip = true
rustflags = [
    "-C",
    "target-cpu=native",
    "-Z",
    "location-detail=none",
    "-Z",
    "fmt-debug=none",
]
